import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { CSSpage, CSScentered } from '@/styles/styles'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={CSSpage}>
        <div style={CSScentered}>
          <h1>
            Welcome to Spicy Game!
          </h1>
          <Link href="/play">Login</Link>

        </div>
      </main>
    </>
  )
}
