import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { CSSpage, CSScentered } from '@/styles/styles'
import { initFirebase } from '@/utils/firebase'

import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useAuthState } from 'react-firebase-hooks/auth'

import Router, { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {


  const app = initFirebase();
  const provider = new GoogleAuthProvider();
  const auth = getAuth();
  const [user, loading] = useAuthState(auth);
  const router = useRouter();

  if (loading) {
    return <div>Loading...</div>
  }

  if (user) {
    console.log(user.displayName);
    router.push("/play")
  }

  const signIn = async () => {
    const result = await(signInWithPopup(auth,provider));
    console.log(result.user);
  }

  return (
    <>
      <Head>
        <title>Spicy Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={CSSpage}>
        <div style={CSScentered}>
          <h1>
            Welcome to Spicy Game!
          </h1>
          <button onClick={signIn}>Sign In</button>

        </div>
      </main>
    </>
  )
}
