import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Game } from '@/components/Game/game'
import { Navbar } from '@/components/Navbar/navbar'
import { CSSpage} from '@/styles/styles'
import { Box } from '@mui/material'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Play</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={CSSpage}>

      <Navbar />
      <Box sx={{
        textAlign: 'center', position: 'absolute', top: '50%', left: '50%', transform: "translate(-50%, -50%)"
      }}>
        <Game />
      </Box>

      </main>

    </>
  )
}
